#ifndef FILOPOW_CHAINPARAMSSEEDS_H
#define FILOPOW_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the filopow network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x2d,0x4c,0x92,0x96}, 7767},  // 45.76.146.150 (seed1)
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // FILOPOW_CHAINPARAMSSEEDS_H
